name: dtic
channels:
  - pytorch
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - blas=1.0
  - ca-certificates=2020.1.1
  - certifi=2020.4.5.2
  - cudatoolkit=10.1.243
  - freetype=2.9.1
  - h5py=2.10.0
  - hdf5=1.10.4
  - intel-openmp=2020.1
  - joblib=0.15.1
  - jpeg=9b
  - ld_impl_linux-64=2.33.1
  - libedit=3.1.20181209
  - libffi=3.3
  - libgcc-ng=9.1.0
  - libgfortran-ng=7.3.0
  - libpng=1.6.37
  - libstdcxx-ng=9.1.0
  - libtiff=4.1.0
  - lz4-c=1.9.2
  - mkl=2020.1
  - mkl-service=2.3.0
  - mkl_fft=1.0.15
  - mkl_random=1.1.1
  - ncurses=6.2
  - ninja=1.9.0
  - numpy=1.18.1
  - numpy-base=1.18.1
  - olefile=0.46
  - openssl=1.1.1g
  - pillow=7.1.2
  - pip=20.0.2
  - python=3.7.7
  - pytorch=1.5.0
  - pyyaml=5.3.1
  - readline=8.0
  - scikit-learn=0.22.1
  - scipy=1.4.1
  - setuptools=47.1.1
  - six=1.15.0
  - sqlite=3.31.1
  - tk=8.6.8
  - toolz=0.10.0
  - torchvision=0.6.0
  - wheel=0.34.2
  - xz=5.2.5
  - yaml=0.1.7
  - zlib=1.2.11
  - zstd=1.4.4
  - pip:
    - chardet==3.0.4
    - decorator==4.4.2
    - future==0.18.2
    - idna==2.9
    - imageio==2.8.0
    - imageio-ffmpeg==0.4.2
    - instagram-scraper==1.9.0
    - kornia==0.3.0
    - moviepy==1.0.3
    - proglog==0.1.9
    - requests==2.23.0
    - tqdm==4.46.1
    - urllib3==1.25.9
