dataset:
  name: frgc
model:
  name: dtikmeans
  n_prototypes: 20
  encoder_name: resnet20
  transformation_sequence: color_affine_tps
  curriculum_learning: [150, 300]
  grid_size: 4
training:
  batch_size: 128
  optimizer:
    name: adam
    lr: 1.0e-3
    weight_decay: 1.0e-6
  scheduler:
    name: multi_step
    gamma: 0.1
    milestones: [550]
    update_range: epoch
  n_epoches: 600
  train_stat_interval: 10
  val_stat_interval: 20
  check_cluster_interval: 20
  seed: 8903
