dataset:
  name: instagram
  tag: santaphoto
  img_size: 128
model:
  name: dtigmm
  n_prototypes: 40
  encoder_name: resnet18
  transformation_sequence: identity_color_proj
  curriculum_learning: [5, 15]
  init_type: sample
  diag_color: True
training:
  batch_size: 64
  optimizer:
    name: adam
    lr: 1.0e-3
    weight_decay: 1.0e-6
  scheduler:
    name: multi_step
    gamma: 0.1
    milestones: [100]
    update_range: epoch
  n_epoches: 110
  train_stat_interval: 50
  val_stat_interval: 100
  check_cluster_interval: 100
  seed: 7832
