dataset:
  name: mnist_1k
model:
  name: dtikmeans
  n_prototypes: 10
  encoder_name: resnet20
  transformation_sequence: identity_affine_morpho_tps
  curriculum_learning: [100, 500, 700]
  grid_size: 4
  kernel_size: 7
training:
  batch_size: 100
  optimizer:
    name: adam
    lr: 1.0e-3
    transformer:
      weight_decay: 1.0e-6
  scheduler:
    name: multi_step
    gamma: 0.1
    milestones: [1200]
    update_range: epoch
  n_epoches: 1700
  train_stat_interval: 20
  val_stat_interval: 40
  check_cluster_interval: 40
  seed: 6065
  visualizer_port:
