dataset:
  name: mnist_test
model:
  name: dtikmeans
  n_prototypes: 10
  encoder_name: resnet20
  transformation_sequence: affine_morpho_tps
  curriculum_learning: [100, 150]
  grid_size: 4
  kernel_size: 7
training:
  batch_size: 128
  optimizer:
    name: adam
    lr: 1.0e-3
    transformer:
      weight_decay: 0
  scheduler:
    name: multi_step
    gamma: 0.1
    milestones: [200]
    update_range: epoch
  n_epoches: 220
  train_stat_interval: 25
  val_stat_interval: 50
  check_cluster_interval: 50
  seed: 6091
