dataset:
  name: svhn
model:
  name: dtikmeans
  n_prototypes: 10
  encoder_name: resnet20
  transformation_sequence: color_projective
  curriculum_learning: [10]
  grid_size: 4
  gaussian_weights: False
  gaussian_weights_std: 7
training:
  batch_size: 128
  optimizer:
    name: adam
    lr: 1.0e-3
    transformer:
      weight_decay: 0
  scheduler:
    name: multi_step
    gamma: 0.1
    milestones: [20]
    update_range: epoch
  n_epoches: 25
  train_stat_interval: 500
  val_stat_interval: 1000
  check_cluster_interval: 100
  seed: 146
